name: Test

on:
  push:
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  test_coverage:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install Flit
        run: pip install flit
      - name: Install Dependencies
        run: flit install --symlink
      - name: Test
        run: make test-cov
      - name: Coverage
        uses: codecov/codecov-action@v3.1.4
